[empty]
add_newline = true
command_timeout = 200
format = "[$directory$git_branch$git_status]($style)$character"

[character]
error_symbol = "[\u2717](bold cyan)"
success_symbol = "[\u276f](bold cyan)"

[directory]
truncation_length = 2
truncation_symbol = "\u2026/"
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "italic cyan"

[git_status]
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "\u21e1${count} "
diverged   = "\u21d5\u21e1${ahead_count}\u21e3${behind_count} "
behind     = "\u21e3${count} "
conflicted = "\uebab "
up_to_date = "\uf00c "
untracked  = "? "
modified   = "\uea71 "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""
